export {};

const $ = <T extends Element>(selector: string) => document.querySelector<T>(selector)!;
const canvas = $("#canvas") as HTMLCanvasElement;
const context = canvas.getContext("webgl", { antialias: false, premultipliedAlpha: true });
if (!context) throw new Error("WebGL is required for Gaussian Splat Render Lab.");
const gl: WebGLRenderingContext = context;
const maxSplats = 40000;
const sourcePositions = new Float32Array(maxSplats * 3);
const sourceColors = new Float32Array(maxSplats * 4);
const visiblePositions = new Float32Array(maxSplats * 3);
const visibleColors = new Float32Array(maxSplats * 4);
let seed = 0x3d71a9;
const random = () => ((seed = (seed * 1664525 + 1013904223) >>> 0) / 4294967296);
for (let index = 0; index < maxSplats; index++) {
  const a = random() * Math.PI * 2, b = random() * Math.PI * 2, radius = Math.pow(random(), .42) * 4.7;
  const x = Math.cos(a) * radius + Math.sin(b * 3) * .45, y = (random() - .5) * 3.5 + Math.sin(a * 2) * .55, z = Math.sin(a) * radius + Math.cos(b * 2) * .45;
  sourcePositions.set([x, y, z], index * 3);
  const warm = .35 + Math.max(0, y) * .12; sourceColors.set([.2 + warm, .55 + random() * .35, .9 - warm * .3, .12 + random() * .25], index * 4);
}
const state = { budget: 40000, lod: 1, radius: 24, culling: true, orbit: true, yaw: .65, pitch: .28, distance: 10, pointer: null as null | { x: number; y: number }, visible: 0, rejected: 0 };
function shader(type: number, source: string) { const result = gl!.createShader(type)!; gl!.shaderSource(result, source); gl!.compileShader(result); if (!gl!.getShaderParameter(result, gl!.COMPILE_STATUS)) throw new Error(gl!.getShaderInfoLog(result) || "shader compile error"); return result; }
function program(vertex: string, fragment: string) { const result = gl!.createProgram()!; gl!.attachShader(result, shader(gl!.VERTEX_SHADER, vertex)); gl!.attachShader(result, shader(gl!.FRAGMENT_SHADER, fragment)); gl!.linkProgram(result); if (!gl!.getProgramParameter(result, gl!.LINK_STATUS)) throw new Error(gl!.getProgramInfoLog(result) || "program link error"); return result; }
const renderProgram = program(`attribute vec3 aPosition;attribute vec4 aColor;uniform mat4 uViewProjection;uniform float uPointSize;varying vec4 vColor;void main(){gl_Position=uViewProjection*vec4(aPosition,1.0);gl_PointSize=uPointSize/max(.1,gl_Position.w);vColor=aColor;}`, `precision mediump float;varying vec4 vColor;void main(){vec2 p=gl_PointCoord*2.0-1.0;float g=exp(-dot(p,p)*4.2);if(g<.018)discard;gl_FragColor=vec4(vColor.rgb*g,vColor.a*g);}`);
const positionBuffer = gl.createBuffer()!, colorBuffer = gl.createBuffer()!;
const positionLocation = gl.getAttribLocation(renderProgram, "aPosition"), colorLocation = gl.getAttribLocation(renderProgram, "aColor"), vpLocation = gl.getUniformLocation(renderProgram, "uViewProjection"), radiusLocation = gl.getUniformLocation(renderProgram, "uPointSize");
function multiply(a: number[], b: number[]) { const out = Array(16).fill(0); for (let r=0;r<4;r++) for (let c=0;c<4;c++) for (let k=0;k<4;k++) out[c*4+r]+=a[k*4+r]*b[c*4+k]; return out; }
function normalize(v: number[]) { const d=Math.hypot(...v)||1; return v.map(n=>n/d); } function cross(a:number[],b:number[]){return[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];} function sub(a:number[],b:number[]){return a.map((n,i)=>n-b[i]);}
function perspective(fov:number,aspect:number,near:number,far:number){const f=1/Math.tan(fov/2),nf=1/(near-far);return[f/aspect,0,0,0,0,f,0,0,0,0,(far+near)*nf,-1,0,0,2*far*near*nf,0];}
function lookAt(eye:number[],target:number[]){const z=normalize(sub(eye,target)),x=normalize(cross([0,1,0],z)),y=cross(z,x);return[x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-x.reduce((s,n,i)=>s+n*eye[i],0),-y.reduce((s,n,i)=>s+n*eye[i],0),-z.reduce((s,n,i)=>s+n*eye[i],0),1];}
function rebuildVisible(eye:number[], forward:number[], right:number[], up:number[], aspect:number) {
  const stride = Math.max(1, Math.round(1 / state.lod)); let visible=0, rejected=0, write=0; const tan = Math.tan(Math.PI/8);
  for (let index=0; index<state.budget; index+=stride) { const offset=index*3, x=sourcePositions[offset],y=sourcePositions[offset+1],z=sourcePositions[offset+2]; const dx=x-eye[0],dy=y-eye[1],dz=z-eye[2], depth=dx*forward[0]+dy*forward[1]+dz*forward[2], horizontal=dx*right[0]+dy*right[1]+dz*right[2], vertical=dx*up[0]+dy*up[1]+dz*up[2]; const inside=!state.culling||(depth>.1&&depth<45&&Math.abs(horizontal)<depth*tan*aspect&&Math.abs(vertical)<depth*tan); if(!inside){rejected++;continue;} visiblePositions.set(sourcePositions.subarray(offset,offset+3),write*3); visibleColors.set(sourceColors.subarray(index*4,index*4+4),write*4); write++;visible++; }
  state.visible=visible; state.rejected=Math.ceil(state.budget/stride)-visible; gl!.bindBuffer(gl!.ARRAY_BUFFER,positionBuffer);gl!.bufferData(gl!.ARRAY_BUFFER,visiblePositions.subarray(0,visible*3),gl!.DYNAMIC_DRAW);gl!.bindBuffer(gl!.ARRAY_BUFFER,colorBuffer);gl!.bufferData(gl!.ARRAY_BUFFER,visibleColors.subarray(0,visible*4),gl!.DYNAMIC_DRAW);
}
function render(now:number) { const width=Math.max(1,canvas.clientWidth*devicePixelRatio),height=Math.max(1,canvas.clientHeight*devicePixelRatio);if(canvas.width!==width||canvas.height!==height){canvas.width=width;canvas.height=height;}if(state.orbit)state.yaw+=.0016;const eye=[Math.sin(state.yaw)*Math.cos(state.pitch)*state.distance,Math.sin(state.pitch)*state.distance,Math.cos(state.yaw)*Math.cos(state.pitch)*state.distance],forward=normalize(eye.map(n=>-n)),right=normalize(cross(forward,[0,1,0])),up=cross(right,forward);rebuildVisible(eye,forward,right,up,width/height);gl.viewport(0,0,width,height);gl.clearColor(.02,.04,.08,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.enable(gl.BLEND);gl.blendFunc(gl.ONE,gl.ONE_MINUS_SRC_ALPHA);gl.useProgram(renderProgram);gl.uniformMatrix4fv(vpLocation,false,new Float32Array(multiply(perspective(Math.PI/4,width/height,.1,45),lookAt(eye,[0,0,0]))));gl.uniform1f(radiusLocation,state.radius*devicePixelRatio);gl.bindBuffer(gl.ARRAY_BUFFER,positionBuffer);gl.enableVertexAttribArray(positionLocation);gl.vertexAttribPointer(positionLocation,3,gl.FLOAT,false,0,0);gl.bindBuffer(gl.ARRAY_BUFFER,colorBuffer);gl.enableVertexAttribArray(colorLocation);gl.vertexAttribPointer(colorLocation,4,gl.FLOAT,false,0,0);gl.drawArrays(gl.POINTS,0,state.visible); metrics(now); requestAnimationFrame(render); }
let fpsLast=performance.now(),frames=0;function metrics(now:number){frames++;if(now-fpsLast>500){$("#fps").textContent=String(Math.round(frames*1000/(now-fpsLast)));fpsLast=now;frames=0;}$("#drawn").textContent=state.visible.toLocaleString();$("#rejected").textContent=state.rejected.toLocaleString();}
function bind(id:string,key:"budget"|"lod"|"radius",format:(value:number)=>string){const input=$("#"+id)as HTMLInputElement;input.addEventListener("input",()=>{const value=Number(input.value);(state as any)[key]=key==="lod"?value/100:value;$("#"+id+"-out").textContent=format(value);});}bind("budget","budget",v=>v.toLocaleString());bind("lod","lod",v=>v+"%");bind("radius","radius",v=>v+" px");($("#culling")as HTMLInputElement).onchange=e=>{state.culling=(e.target as HTMLInputElement).checked;$("#cull-badge").textContent=state.culling?"frustum culling on":"culling off"};($("#orbit")as HTMLInputElement).onchange=e=>state.orbit=(e.target as HTMLInputElement).checked;
canvas.addEventListener("pointerdown",e=>{state.pointer={x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);});canvas.addEventListener("pointermove",e=>{if(!state.pointer)return;state.orbit=false;state.yaw+=(e.clientX-state.pointer.x)*.008;state.pitch=Math.max(-1.3,Math.min(1.3,state.pitch+(e.clientY-state.pointer.y)*.008));state.pointer={x:e.clientX,y:e.clientY};});canvas.addEventListener("pointerup",()=>state.pointer=null);canvas.addEventListener("wheel",e=>{e.preventDefault();state.distance=Math.max(4,Math.min(25,state.distance*(e.deltaY>0?1.1:.9)));},{passive:false});requestAnimationFrame(render);
