(() => {
  "use strict";

  // ECS world: entities are IDs, while all state lives in named component stores.
  class World {
    constructor() { this.nextId = 1; this.entities = new Set(); this.components = new Map(); }
    createEntity() { const id = this.nextId++; this.entities.add(id); return id; }
    destroyEntity(id) { this.entities.delete(id); for (const store of this.components.values()) store.delete(id); }
    clear() { this.entities.clear(); this.components.clear(); this.nextId = 1; }
    add(id, type, value) { if (!this.components.has(type)) this.components.set(type, new Map()); this.components.get(type).set(id, value); return value; }
    get(id, type) { return this.components.get(type)?.get(id); }
    has(id, type) { return this.components.get(type)?.has(id) ?? false; }
    query(...types) { return [...this.entities].filter((id) => types.every((type) => this.has(id, type))); }
  }

  const world = new World();
  const state = {
    selected: null, wireframe: false, gridVisible: true, snap: true, gridSize: 1, tool: "select",
    camera: { yaw: .72, pitch: .42, distance: 10, target: [0, 0, 0] },
    pointer: { active: false, moved: false, x: 0, y: 0, gesture: null },
    history: { undo: [], redo: [] }, lastViewProjection: null,
  };
  const $ = (selector) => document.querySelector(selector);
  const canvas = $("#viewport");
  const status = $("#status");
  const list = $("#entity-list");
  const inputs = [...document.querySelectorAll("[data-component] input")];

  function setStatus(message) { status.textContent = message; }
  function makeTransform(position = [0, 0, 0]) { return { position: [...position], rotation: [0, 0, 0], scale: [1, 1, 1], matrix: identity() }; }
  function hexToRgb(hex) { const n = Number.parseInt(hex.slice(1), 16); return [((n >> 16) & 255) / 255, ((n >> 8) & 255) / 255, (n & 255) / 255]; }
  function rgbToHex(rgb) { return "#" + rgb.map((value) => Math.round(Math.max(0, Math.min(1, value)) * 255).toString(16).padStart(2, "0")).join(""); }
  function clamp(value, min, max) { return Math.max(min, Math.min(max, value)); }
  function snap(value) { return state.snap ? Math.round(value / state.gridSize) * state.gridSize : value; }
  function clean(value) { return Number(value.toFixed(3)); }
  function escapeHtml(value) { const element = document.createElement("span"); element.textContent = value; return element.innerHTML; }

  // Matrix helpers kept dependency-free so the demo remains copyable.
  function identity() { return [1,0,0,0, 0,1,0,0, 0,0,1,0, 0,0,0,1]; }
  function multiply(a, b) { const out = new Array(16).fill(0); for (let row = 0; row < 4; row++) for (let col = 0; col < 4; col++) for (let k = 0; k < 4; k++) out[col * 4 + row] += a[k * 4 + row] * b[col * 4 + k]; return out; }
  function perspective(fov, aspect, near, far) { const f = 1 / Math.tan(fov / 2); const nf = 1 / (near - far); return [f/aspect,0,0,0, 0,f,0,0, 0,0,(far+near)*nf,-1, 0,0,2*far*near*nf,0]; }
  function normalize(v) { const length = Math.hypot(...v) || 1; return v.map((n) => n / length); }
  function cross(a, b) { return [a[1]*b[2]-a[2]*b[1], a[2]*b[0]-a[0]*b[2], a[0]*b[1]-a[1]*b[0]]; }
  function subtract(a, b) { return a.map((n, i) => n - b[i]); }
  function lookAt(eye, target, up = [0,1,0]) { const z = normalize(subtract(eye, target)); const x = normalize(cross(up, z)); const y = cross(z, x); return [x[0],y[0],z[0],0, x[1],y[1],z[1],0, x[2],y[2],z[2],0, -x.reduce((s,n,i)=>s+n*eye[i],0),-y.reduce((s,n,i)=>s+n*eye[i],0),-z.reduce((s,n,i)=>s+n*eye[i],0),1]; }
  function transformMatrix(transform) {
    const [x,y,z] = transform.rotation.map((degree) => degree * Math.PI / 180); const [sx,sy,sz] = transform.scale; const [tx,ty,tz] = transform.position;
    const cx=Math.cos(x), sxr=Math.sin(x), cy=Math.cos(y), syr=Math.sin(y), cz=Math.cos(z), szr=Math.sin(z);
    const rx=[1,0,0,0, 0,cx,sxr,0, 0,-sxr,cx,0, 0,0,0,1], ry=[cy,0,-syr,0, 0,1,0,0, syr,0,cy,0, 0,0,0,1], rz=[cz,szr,0,0, -szr,cz,0,0, 0,0,1,0, 0,0,0,1];
    const scale=[sx,0,0,0, 0,sy,0,0, 0,0,sz,0, 0,0,0,1], translate=[1,0,0,0, 0,1,0,0, 0,0,1,0, tx,ty,tz,1];
    return multiply(translate, multiply(rz, multiply(ry, multiply(rx, scale))));
  }
  function transformPoint(matrix, point) { const [x,y,z] = point; const w = matrix[3]*x + matrix[7]*y + matrix[11]*z + matrix[15]; return [(matrix[0]*x + matrix[4]*y + matrix[8]*z + matrix[12])/w, (matrix[1]*x + matrix[5]*y + matrix[9]*z + matrix[13])/w, (matrix[2]*x + matrix[6]*y + matrix[10]*z + matrix[14])/w]; }
  function transformVec4(matrix, vector) { const [x,y,z,w] = vector; return [matrix[0]*x+matrix[4]*y+matrix[8]*z+matrix[12]*w, matrix[1]*x+matrix[5]*y+matrix[9]*z+matrix[13]*w, matrix[2]*x+matrix[6]*y+matrix[10]*z+matrix[14]*w, matrix[3]*x+matrix[7]*y+matrix[11]*z+matrix[15]*w]; }
  function inverse(m) {
    const out = new Array(16); const a00=m[0],a01=m[1],a02=m[2],a03=m[3],a10=m[4],a11=m[5],a12=m[6],a13=m[7],a20=m[8],a21=m[9],a22=m[10],a23=m[11],a30=m[12],a31=m[13],a32=m[14],a33=m[15];
    const b00=a00*a11-a01*a10,b01=a00*a12-a02*a10,b02=a00*a13-a03*a10,b03=a01*a12-a02*a11,b04=a01*a13-a03*a11,b05=a02*a13-a03*a12,b06=a20*a31-a21*a30,b07=a20*a32-a22*a30,b08=a20*a33-a23*a30,b09=a21*a32-a22*a31,b10=a21*a33-a23*a31,b11=a22*a33-a23*a32;
    let det=b00*b11-b01*b10+b02*b09+b03*b08-b04*b07+b05*b06; if (!det) return null; det=1/det;
    out[0]=(a11*b11-a12*b10+a13*b09)*det; out[1]=(a02*b10-a01*b11-a03*b09)*det; out[2]=(a31*b05-a32*b04+a33*b03)*det; out[3]=(a22*b04-a21*b05-a23*b03)*det; out[4]=(a12*b08-a10*b11-a13*b07)*det; out[5]=(a00*b11-a02*b08+a03*b07)*det; out[6]=(a32*b02-a30*b05-a33*b01)*det; out[7]=(a20*b05-a22*b02+a23*b01)*det; out[8]=(a10*b10-a11*b08+a13*b06)*det; out[9]=(a01*b08-a00*b10-a03*b06)*det; out[10]=(a30*b04-a31*b02+a33*b00)*det; out[11]=(a21*b02-a20*b04-a23*b00)*det; out[12]=(a11*b07-a10*b09-a12*b06)*det; out[13]=(a00*b09-a01*b07+a02*b06)*det; out[14]=(a31*b01-a30*b03-a32*b00)*det; out[15]=(a20*b03-a21*b01+a22*b00)*det; return out;
  }
  function groundPoint(clientX, clientY) {
    if (!state.lastViewProjection) return null; const rect = canvas.getBoundingClientRect(); const x=(clientX-rect.left)/rect.width*2-1, y=1-(clientY-rect.top)/rect.height*2; const inv=inverse(state.lastViewProjection); if (!inv) return null;
    const near=transformVec4(inv,[x,y,-1,1]), far=transformVec4(inv,[x,y,1,1]); const a=near.slice(0,3).map((n,i)=>n/near[3]), b=far.slice(0,3).map((n,i)=>n/far[3]); const dir=normalize(subtract(b,a)); if (Math.abs(dir[1]) < .0001) return null; const t=-a[1]/dir[1]; return t < 0 ? null : [a[0]+dir[0]*t,0,a[2]+dir[2]*t];
  }

  function cubeMesh() { return makeMesh([-1,-1,-1, 1,-1,-1, 1,1,-1, -1,1,-1, -1,-1,1, 1,-1,1, 1,1,1, -1,1,1], [0,1,2,0,2,3, 1,5,6,1,6,2, 5,4,7,5,7,6, 4,0,3,4,3,7, 3,2,6,3,6,7, 4,5,1,4,1,0]); }
  function makeMesh(positions, indices) {
    const normals=new Array(positions.length).fill(0); for(let i=0;i<indices.length;i+=3){const a=indices[i]*3,b=indices[i+1]*3,c=indices[i+2]*3,ab=[positions[b]-positions[a],positions[b+1]-positions[a+1],positions[b+2]-positions[a+2]],ac=[positions[c]-positions[a],positions[c+1]-positions[a+1],positions[c+2]-positions[a+2]],n=cross(ab,ac); for(const index of [a,b,c]){normals[index]+=n[0];normals[index+1]+=n[1];normals[index+2]+=n[2];}} for(let i=0;i<normals.length;i+=3){const n=normalize(normals.slice(i,i+3));normals[i]=n[0];normals[i+1]=n[1];normals[i+2]=n[2];} return {positions,normals,indices,gpu:null};
  }
  function parseObj(text) {
    const positions=[],indices=[]; for(const rawLine of text.split(/\r?\n/)){const line=rawLine.trim();if(!line||line.startsWith("#"))continue;const fields=line.split(/\s+/);if(fields[0]==="v"&&fields.length>=4)positions.push(Number(fields[1]),Number(fields[2]),Number(fields[3]));if(fields[0]==="f"&&fields.length>=4){const face=fields.slice(1).map((value)=>{const index=Number(value.split("/")[0]);return index<0?positions.length/3+index:index-1;});for(let i=1;i<face.length-1;i++)indices.push(face[0],face[i],face[i+1]);}}
    if(positions.length<9||indices.length<3||positions.some((n)=>!Number.isFinite(n))||indices.some((n)=>n<0||n*3>=positions.length))throw new Error("No supported OBJ geometry found. Use v and f records."); if(positions.length/3>65535)throw new Error("This demo supports OBJ files with up to 65,535 vertices."); return makeMesh(positions,indices);
  }

  // WebGL render system.
  const gl=canvas.getContext("webgl",{antialias:true}); if(!gl){setStatus("WebGL is unavailable in this browser. Try a current desktop browser.");return;}
  const vertexSource=`attribute vec3 aPosition;attribute vec3 aNormal;uniform mat4 uModel;uniform mat4 uView;uniform mat4 uProjection;varying vec3 vNormal;varying vec3 vWorld;void main(){vec4 world=uModel*vec4(aPosition,1.0);vWorld=world.xyz;vNormal=mat3(uModel)*aNormal;gl_Position=uProjection*uView*world;}`;
  const fragmentSource=`precision mediump float;uniform vec3 uColor;uniform vec3 uLight;uniform bool uSelected;varying vec3 vNormal;varying vec3 vWorld;void main(){vec3 n=normalize(vNormal);float light=max(dot(n,normalize(uLight)),0.0);float rim=pow(1.0-max(dot(n,normalize(-vWorld)),0.0),2.0);vec3 base=uColor*(0.24+0.76*light)+vec3(0.05)*rim;if(uSelected)base=mix(base,vec3(0.49,0.95,0.78),0.36);gl_FragColor=vec4(base,1.0);}`;
  function shader(type,source){const result=gl.createShader(type);gl.shaderSource(result,source);gl.compileShader(result);if(!gl.getShaderParameter(result,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(result));return result;}
  function program(vertex,fragment){const result=gl.createProgram();gl.attachShader(result,shader(gl.VERTEX_SHADER,vertex));gl.attachShader(result,shader(gl.FRAGMENT_SHADER,fragment));gl.linkProgram(result);if(!gl.getProgramParameter(result,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(result));return result;}
  const renderProgram=program(vertexSource,fragmentSource); const locations={position:gl.getAttribLocation(renderProgram,"aPosition"),normal:gl.getAttribLocation(renderProgram,"aNormal"),model:gl.getUniformLocation(renderProgram,"uModel"),view:gl.getUniformLocation(renderProgram,"uView"),projection:gl.getUniformLocation(renderProgram,"uProjection"),color:gl.getUniformLocation(renderProgram,"uColor"),light:gl.getUniformLocation(renderProgram,"uLight"),selected:gl.getUniformLocation(renderProgram,"uSelected")};
  function ensureGpu(mesh){if(mesh.gpu)return mesh.gpu;const gpu={position:gl.createBuffer(),normal:gl.createBuffer(),index:gl.createBuffer(),count:mesh.indices.length};gl.bindBuffer(gl.ARRAY_BUFFER,gpu.position);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(mesh.positions),gl.STATIC_DRAW);gl.bindBuffer(gl.ARRAY_BUFFER,gpu.normal);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(mesh.normals),gl.STATIC_DRAW);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,gpu.index);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,new Uint16Array(mesh.indices),gl.STATIC_DRAW);mesh.gpu=gpu;return gpu;}
  const grid=(()=>{const positions=[];for(let n=-12;n<=12;n++){positions.push(n,0,-12,n,0,12,-12,0,n,12,0,n);}const buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(positions),gl.STATIC_DRAW);return{buffer,count:positions.length/3};})();
  const RenderSystem={render(){const width=Math.max(1,canvas.clientWidth*devicePixelRatio),height=Math.max(1,canvas.clientHeight*devicePixelRatio);if(canvas.width!==width||canvas.height!==height){canvas.width=width;canvas.height=height;}gl.viewport(0,0,width,height);gl.enable(gl.DEPTH_TEST);gl.enable(gl.CULL_FACE);gl.clearColor(.027,.04,.065,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);const {yaw,pitch,distance,target}=state.camera;const eye=[target[0]+distance*Math.sin(yaw)*Math.cos(pitch),target[1]+distance*Math.sin(pitch),target[2]+distance*Math.cos(yaw)*Math.cos(pitch)],view=lookAt(eye,target),projection=perspective(Math.PI/4,width/height,.1,200);state.lastViewProjection=multiply(projection,view);gl.useProgram(renderProgram);gl.uniformMatrix4fv(locations.view,false,view);gl.uniformMatrix4fv(locations.projection,false,projection);gl.uniform3f(locations.light,-3,7,5);
    if(state.gridVisible){gl.disable(gl.CULL_FACE);gl.bindBuffer(gl.ARRAY_BUFFER,grid.buffer);gl.enableVertexAttribArray(locations.position);gl.vertexAttribPointer(locations.position,3,gl.FLOAT,false,0,0);gl.disableVertexAttribArray(locations.normal);gl.vertexAttrib3f(locations.normal,0,1,0);gl.uniformMatrix4fv(locations.model,false,identity());gl.uniform3f(locations.color,.18,.29,.41);gl.uniform1i(locations.selected,false);gl.drawArrays(gl.LINES,0,grid.count);gl.enable(gl.CULL_FACE);}
    for(const id of world.query("transform","mesh","material")){const transform=world.get(id,"transform");transform.matrix=transformMatrix(transform);const mesh=world.get(id,"mesh"),material=world.get(id,"material"),gpu=ensureGpu(mesh);gl.bindBuffer(gl.ARRAY_BUFFER,gpu.position);gl.enableVertexAttribArray(locations.position);gl.vertexAttribPointer(locations.position,3,gl.FLOAT,false,0,0);gl.bindBuffer(gl.ARRAY_BUFFER,gpu.normal);gl.enableVertexAttribArray(locations.normal);gl.vertexAttribPointer(locations.normal,3,gl.FLOAT,false,0,0);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,gpu.index);gl.uniformMatrix4fv(locations.model,false,transform.matrix);gl.uniform3fv(locations.color,material.color);gl.uniform1i(locations.selected,id===state.selected);gl.drawElements(state.wireframe?gl.LINES:gl.TRIANGLES,gpu.count,gl.UNSIGNED_SHORT,0);}requestAnimationFrame(()=>RenderSystem.render());}};

  // HistorySystem: scene snapshots make each direct-modeling action reversible.
  // EditorSystem uses these helpers after creates, transforms, imports, and deletes.
  function sceneSnapshot(){return world.query("name","transform","mesh","material").map((id)=>({name:world.get(id,"name").value,mesh:world.get(id,"mesh"),transform:JSON.parse(JSON.stringify(world.get(id,"transform"))),color:[...world.get(id,"material").color]}));}
  function restoreSnapshot(snapshot){world.clear();state.selected=null;for(const item of snapshot){const id=world.createEntity();world.add(id,"name",{value:item.name});world.add(id,"transform",{...item.transform,matrix:identity()});world.add(id,"mesh",item.mesh);world.add(id,"material",{color:[...item.color]});world.add(id,"selectable",{});}refreshUi();}
  function commitHistory(){state.history.undo.push(sceneSnapshot());if(state.history.undo.length>60)state.history.undo.shift();state.history.redo=[];refreshHistoryUi();}
  function undo(){if(state.history.undo.length<2){setStatus("Nothing to undo.");return;}state.history.redo.push(state.history.undo.pop());restoreSnapshot(state.history.undo.at(-1));setStatus("Undo applied.");refreshHistoryUi();}
  function redo(){const snapshot=state.history.redo.pop();if(!snapshot){setStatus("Nothing to redo.");return;}state.history.undo.push(snapshot);restoreSnapshot(snapshot);setStatus("Redo applied.");refreshHistoryUi();}
  function refreshHistoryUi(){$("#undo").disabled=state.history.undo.length<2;$("#redo").disabled=!state.history.redo.length;}
  const EditorSystem={
    createMeshEntity(name,mesh,position=[0,0,0],color="#7cf2c7"){const id=world.createEntity();world.add(id,"name",{value:name});world.add(id,"transform",makeTransform(position));world.add(id,"mesh",mesh);world.add(id,"material",{color:hexToRgb(color)});world.add(id,"selectable",{});return id;},
    createBox(position=[0,0,0]){const count=world.query("mesh").length;const id=this.createMeshEntity(`Box ${count+1}`,cubeMesh(),[clean(position[0]),1,clean(position[2])],count%2?"#7ab8ff":"#7cf2c7");this.select(id,`Placed Box ${count+1}. Use Move, Rotate, or Push/Pull.`);commitHistory();},
    select(id,message){state.selected=id;refreshUi();if(message)setStatus(message);else setStatus(id?`Selected ${world.get(id,"name").value}. Choose a modeling tool or edit its components.`:"Selection cleared.");},
    deleteSelected(){if(!state.selected)return;const name=world.get(state.selected,"name")?.value||"entity";world.destroyEntity(state.selected);state.selected=null;refreshUi();commitHistory();setStatus(`Deleted ${name}.`);},
    duplicateSelected(){if(!state.selected){setStatus("Select a mesh to duplicate.");return;}const source=state.selected,t=world.get(source,"transform"),name=world.get(source,"name").value,mesh=world.get(source,"mesh"),color=rgbToHex(world.get(source,"material").color),id=this.createMeshEntity(`${name} copy`,mesh,[t.position[0]+state.gridSize,t.position[1],t.position[2]+state.gridSize],color);const next=world.get(id,"transform");next.rotation=[...t.rotation];next.scale=[...t.scale];this.select(id,`Duplicated ${name}.`);commitHistory();},
    pick(clientX,clientY){const rect=canvas.getBoundingClientRect(),x=clientX-rect.left,y=clientY-rect.top;let closest=null,distance=Infinity;for(const id of world.query("transform","selectable")){const transform=world.get(id,"transform"),clip=transformPoint(multiply(state.lastViewProjection,transform.matrix),[0,0,0]),sx=(clip[0]*.5+.5)*rect.width,sy=(-clip[1]*.5+.5)*rect.height,d=Math.hypot(sx-x,sy-y);if(clip[2]>-1&&clip[2]<1&&d<distance){closest=id;distance=d;}}if(distance<62)this.select(closest);else this.select(null);},
    frameSelected(){if(!state.selected){setStatus("Select an entity before framing it.");return;}state.camera.target=[...world.get(state.selected,"transform").position];state.camera.distance=6;setStatus(`Camera framed ${world.get(state.selected,"name").value}.`);},
    homeView(){state.camera={yaw:.72,pitch:.42,distance:10,target:[0,0,0]};setStatus("Home view restored.");},
    topView(){state.camera={yaw:0,pitch:1.45,distance:14,target:[0,0,0]};setStatus("Top view enabled. Use Home view to return.");},
    groundSelected(){if(!state.selected)return;const t=world.get(state.selected,"transform");t.position[1]=clean(t.scale[1]);refreshUi();commitHistory();setStatus("Selected mesh dropped onto the ground plane.");},
    resetTransform(){if(!state.selected)return;const t=world.get(state.selected,"transform");t.position=[0,clean(t.scale[1]),0];t.rotation=[0,0,0];t.scale=[1,1,1];refreshUi();commitHistory();setStatus("Selected transform reset.");},
  };

  function toolCopy(tool){return {select:"Select: click a mesh · drag empty space to orbit",box:"Box: click the grid to place a unit box",move:"Move: drag a selected mesh along the ground",rotate:"Rotate: drag left or right around Y",pushpull:"Push/Pull: drag up or down to change height"}[tool];}
  function setTool(tool){state.tool=tool;for(const button of document.querySelectorAll("[data-tool]"))button.setAttribute("aria-pressed",String(button.dataset.tool===tool));$("#active-tool").textContent=tool==="pushpull"?"Push/Pull":tool[0].toUpperCase()+tool.slice(1);$("#tool-hint").textContent=toolCopy(tool);canvas.className=`tool-${tool}`;setStatus(toolCopy(tool));}
  function refreshUi(){const ids=world.query("name","transform","mesh"),selected=state.selected;$("#entity-count").textContent=String(ids.length);list.innerHTML="";if(!ids.length)list.innerHTML='<p class="empty">The scene is empty. Place a box or import an OBJ file.</p>';for(const id of ids){const name=world.get(id,"name").value,mesh=world.get(id,"mesh"),button=document.createElement("button");button.type="button";button.className="entity";button.setAttribute("aria-selected",String(id===selected));button.innerHTML=`<span class="entity-icon">◇</span><span><span class="entity-name">${escapeHtml(name)}</span><span class="entity-meta">${mesh.indices.length/3} faces · entity ${id}</span></span>`;button.addEventListener("click",()=>EditorSystem.select(id));list.append(button);}
    const selectedName=$("#selected-name");for(const input of inputs)input.disabled=!selected;for(const button of [$("#delete-selected"),$("#duplicate"),$("#ground-selected"),$("#reset-transform")])button.disabled=!selected;$("#material-color").disabled=!selected;$("#color-picker").disabled=!selected;if(!selected){selectedName.textContent="No entity selected.";return;}const name=world.get(selected,"name").value,t=world.get(selected,"transform"),material=world.get(selected,"material");selectedName.innerHTML=`<strong>${escapeHtml(name)}</strong>Entity ${selected} · transform + mesh + material`;for(const component of ["position","rotation","scale"])for(const input of document.querySelectorAll(`[data-component="${component}"] input`))input.value=t[component][["x","y","z"].indexOf(input.dataset.axis)];const color=rgbToHex(material.color);$("#material-color").value=color;$("#color-picker").value=color;
  }
  function updateTransformFromInput(event){if(!state.selected)return;const input=event.currentTarget,component=input.closest("[data-component]").dataset.component,axis=["x","y","z"].indexOf(input.dataset.axis),value=Number(input.value);if(Number.isFinite(value)){world.get(state.selected,"transform")[component][axis]=component==="scale"?Math.max(.05,value):value;}}

  // Input system: select/orbit and the three lightweight direct-modeling tools.
  canvas.addEventListener("pointerdown",(event)=>{canvas.setPointerCapture(event.pointerId);canvas.focus();const selected=state.selected;state.pointer={active:true,moved:false,x:event.clientX,y:event.clientY,gesture:null};if(selected&&["move","rotate","pushpull"].includes(state.tool)){const t=world.get(selected,"transform");state.pointer.gesture={id:selected,tool:state.tool,transform:{position:[...t.position],rotation:[...t.rotation],scale:[...t.scale]}};}});
  canvas.addEventListener("pointermove",(event)=>{if(!state.pointer.active)return;const dx=event.clientX-state.pointer.x,dy=event.clientY-state.pointer.y;if(Math.abs(dx)+Math.abs(dy)>2)state.pointer.moved=true;const gesture=state.pointer.gesture;if(gesture){const t=world.get(gesture.id,"transform"),origin=gesture.transform;if(gesture.tool==="move"){t.position=[snap(origin.position[0]+dx*.025),origin.position[1],snap(origin.position[2]+dy*.025)];}if(gesture.tool==="rotate"){const degrees=state.snap?Math.round((origin.rotation[1]+dx*.5)/15)*15:origin.rotation[1]+dx*.5;t.rotation=[origin.rotation[0],clean(degrees),origin.rotation[2]];}if(gesture.tool==="pushpull"){const next=clamp(origin.scale[1]-dy*.018,.1,12);t.scale=[origin.scale[0],state.snap?snap(next):clean(next),origin.scale[2]];t.position=[origin.position[0],clean(t.scale[1]),origin.position[2]];}refreshUi();return;}if(state.tool==="select"){state.camera.yaw-=dx*.008;state.camera.pitch=clamp(state.camera.pitch+dy*.008,-1.45,1.45);}state.pointer.x=event.clientX;state.pointer.y=event.clientY;});
  canvas.addEventListener("pointerup",(event)=>{if(!state.pointer.active)return;const {gesture,moved}=state.pointer;if(gesture&&moved){commitHistory();setStatus(`${gesture.tool==="pushpull"?"Push/Pull":gesture.tool[0].toUpperCase()+gesture.tool.slice(1)} applied.`);}else if(state.tool==="box"&&!moved){const point=groundPoint(event.clientX,event.clientY);if(point)EditorSystem.createBox([snap(point[0]),0,snap(point[2])]);else setStatus("Aim at the ground grid to place a box.");}else if(state.tool==="select"&&!moved){EditorSystem.pick(event.clientX,event.clientY);}state.pointer.active=false;state.pointer.gesture=null;});
  canvas.addEventListener("wheel",(event)=>{event.preventDefault();state.camera.distance=clamp(state.camera.distance*(event.deltaY>0?1.1:.9),2,45);},{passive:false});
  window.addEventListener("keydown",(event)=>{if(document.activeElement?.tagName==="INPUT"||document.activeElement?.tagName==="SELECT")return;const key=event.key.toLowerCase();if((event.metaKey||event.ctrlKey)&&key==="z"){event.preventDefault();event.shiftKey?redo():undo();return;}if(key==="delete"||key==="backspace"){EditorSystem.deleteSelected();return;}if({v:"select",b:"box",m:"move",r:"rotate",p:"pushpull"}[key]){setTool({v:"select",b:"box",m:"move",r:"rotate",p:"pushpull"}[key]);return;}if(key==="g")$("#toggle-wireframe").click();});

  // UI controls bridge directly into the editor systems.
  for(const button of document.querySelectorAll("[data-tool]"))button.addEventListener("click",()=>setTool(button.dataset.tool));
  $("#add-cube").addEventListener("click",()=>EditorSystem.createBox([0,0,0])); $("#duplicate").addEventListener("click",()=>EditorSystem.duplicateSelected()); $("#delete-selected").addEventListener("click",()=>EditorSystem.deleteSelected()); $("#undo").addEventListener("click",undo); $("#redo").addEventListener("click",redo); $("#frame-selected").addEventListener("click",()=>EditorSystem.frameSelected()); $("#home-view").addEventListener("click",()=>EditorSystem.homeView()); $("#top-view").addEventListener("click",()=>EditorSystem.topView()); $("#ground-selected").addEventListener("click",()=>EditorSystem.groundSelected()); $("#reset-transform").addEventListener("click",()=>EditorSystem.resetTransform());
  $("#toggle-wireframe").addEventListener("click",(event)=>{state.wireframe=!state.wireframe;event.currentTarget.setAttribute("aria-pressed",String(state.wireframe));event.currentTarget.querySelector(".tool-name").textContent=state.wireframe?"Solid view":"Wireframe";setStatus(state.wireframe?"Wireframe display enabled.":"Solid display enabled.");});
  $("#toggle-grid").addEventListener("click",(event)=>{state.gridVisible=!state.gridVisible;event.currentTarget.setAttribute("aria-pressed",String(state.gridVisible));event.currentTarget.textContent=state.gridVisible?"Grid on":"Grid off";}); $("#snap-toggle").addEventListener("change",(event)=>{state.snap=event.target.checked;setStatus(state.snap?`Grid snap enabled (${state.gridSize} units).`:"Grid snap disabled.");}); $("#grid-size").addEventListener("change",(event)=>{state.gridSize=Number(event.target.value);setStatus(`Grid increment set to ${state.gridSize} units.`);});
  $("#import-obj").addEventListener("click",()=>$("#obj-file").click()); $("#obj-file").addEventListener("change",async(event)=>{const file=event.target.files?.[0];if(!file)return;try{const mesh=parseObj(await file.text());const id=EditorSystem.createMeshEntity(file.name.replace(/\.obj$/i,"")||"Imported OBJ",mesh,[0,1,0],"#f6b56d");EditorSystem.select(id,`Imported ${file.name}: ${mesh.positions.length/3} vertices, ${mesh.indices.length/3} faces.`);commitHistory();}catch(error){setStatus(`Could not import ${file.name}: ${error.message}`);}finally{event.target.value="";}});
  $("#export-obj").addEventListener("click",()=>{const lines=["# OBJ ECS Editor export"];let offset=0;for(const id of world.query("transform","mesh","name")){const t=world.get(id,"transform"),mesh=world.get(id,"mesh");lines.push(`o ${world.get(id,"name").value.replace(/\s+/g,"_")}`);for(let i=0;i<mesh.positions.length;i+=3){const p=transformPoint(transformMatrix(t),mesh.positions.slice(i,i+3));lines.push(`v ${p.map((n)=>n.toFixed(6)).join(" ")}`);}for(let i=0;i<mesh.indices.length;i+=3)lines.push(`f ${mesh.indices[i]+1+offset} ${mesh.indices[i+1]+1+offset} ${mesh.indices[i+2]+1+offset}`);offset+=mesh.positions.length/3;}const blob=new Blob([lines.join("\n")+"\n"],{type:"text/plain"}),link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download="sketchup-lite-scene.obj";link.click();URL.revokeObjectURL(link.href);setStatus("Exported scene as sketchup-lite-scene.obj.");});
  for(const input of inputs){input.addEventListener("input",updateTransformFromInput);input.addEventListener("change",()=>{if(state.selected){commitHistory();setStatus("Transform component updated.");}});}for(const input of [$("#material-color"),$("#color-picker")])input.addEventListener("input",(event)=>{if(!state.selected||!/^#[\da-f]{6}$/i.test(event.target.value))return;world.get(state.selected,"material").color=hexToRgb(event.target.value);$("#material-color").value=event.target.value;$("#color-picker").value=event.target.value;});

  // Seed the workspace and capture the baseline as history entry zero.
  const starter=EditorSystem.createMeshEntity("Starter cube",cubeMesh(),[0,1,0],"#7cf2c7");const blue=EditorSystem.createMeshEntity("Blue cube",cubeMesh(),[3,.75,-1.6],"#7ab8ff");world.get(blue,"transform").scale=[.75,.75,.75];world.get(blue,"transform").rotation=[0,28,0];EditorSystem.select(starter);commitHistory();setTool("select");RenderSystem.render();
})();
