(() => {
  "use strict";
  const $ = (selector) => document.querySelector(selector);
  const canvas = $("#viewport");
  const ctx = canvas.getContext("2d");
  const AXES = { x: { color: "#ff6978", vector: [1, 0, 0], screen: [1, 0] }, y: { color: "#78db8b", vector: [0, 1, 0], screen: [0, -1] }, z: { color: "#6daeff", vector: [0, 0, 1], screen: [.68, .34] } };
  const state = { tool: "translate", space: "world", snap: true, selectedId: "crate", history: [], redo: [], revision: 0, pickCount: 0, dragCount: 0, drag: null, nextId: 1 };
  const objects = [
    makeObject("crate", "Crate", [-1.5, .2, 0], [0, 0, 0], [1.1, 1.1, 1.1], "#ffb56f"),
    makeObject("drone", "Drone", [1.3, .6, -.7], [15, 32, 0], [.85, .85, .85], "#9fc3ff"),
    makeObject("marker", "Marker", [.2, -1.1, .5], [0, 0, 22], [.65, .65, .65], "#a9f0d6"),
  ];
  function makeObject(id, name, position, euler, scale, color) { return { id, name, position, rotation: quatFromEuler(...euler.map(degToRad)), scale, color }; }
  function degToRad(value) { return value * Math.PI / 180; }
  function radToDeg(value) { return value * 180 / Math.PI; }
  function quatFromEuler(x, y, z) { const cx = Math.cos(x / 2), sx = Math.sin(x / 2), cy = Math.cos(y / 2), sy = Math.sin(y / 2), cz = Math.cos(z / 2), sz = Math.sin(z / 2); return normalizeQuat([sx * cy * cz + cx * sy * sz, cx * sy * cz - sx * cy * sz, cx * cy * sz + sx * sy * cz, cx * cy * cz - sx * sy * sz]); }
  function quatFromAxis(axis, angle) { const s = Math.sin(angle / 2); return [axis[0] * s, axis[1] * s, axis[2] * s, Math.cos(angle / 2)]; }
  function quatMul(a, b) { return [a[3] * b[0] + a[0] * b[3] + a[1] * b[2] - a[2] * b[1], a[3] * b[1] - a[0] * b[2] + a[1] * b[3] + a[2] * b[0], a[3] * b[2] + a[0] * b[1] - a[1] * b[0] + a[2] * b[3], a[3] * b[3] - a[0] * b[0] - a[1] * b[1] - a[2] * b[2]]; }
  function normalizeQuat(q) { const length = Math.hypot(...q) || 1; return q.map((value) => value / length); }
  function quatRotate(q, v) { const p = [v[0], v[1], v[2], 0], inverse = [-q[0], -q[1], -q[2], q[3]]; return quatMul(quatMul(q, p), inverse).slice(0, 3); }
  function quatToEuler(q) { const [x, y, z, w] = q; const sinr = 2 * (w * x + y * z), cosr = 1 - 2 * (x * x + y * y), sinp = 2 * (w * y - z * x), siny = 2 * (w * z + x * y), cosy = 1 - 2 * (y * y + z * z); return [Math.atan2(sinr, cosr), Math.abs(sinp) >= 1 ? Math.sign(sinp) * Math.PI / 2 : Math.asin(sinp), Math.atan2(siny, cosy)].map(radToDeg); }
  function cloneTransform(object) { return { position: [...object.position], rotation: [...object.rotation], scale: [...object.scale] }; }
  function applyTransform(object, value) { object.position = [...value.position]; object.rotation = [...value.rotation]; object.scale = [...value.scale]; }
  function selected() { return objects.find((object) => object.id === state.selectedId); }
  function clamp(value, min, max) { return Math.max(min, Math.min(max, value)); }
  function snap(value, increment) { return state.snap ? Math.round(value / increment) * increment : value; }
  function project(point) { const width = canvas.width / devicePixelRatio, height = canvas.height / devicePixelRatio, scale = Math.min(width, height) * .115; return { x: width / 2 + (point[0] + point[2] * .62) * scale, y: height / 2 - (point[1] - point[2] * .3) * scale, scale }; }
  function resize() { const width = Math.max(1, Math.round(canvas.clientWidth * devicePixelRatio)), height = Math.max(1, Math.round(canvas.clientHeight * devicePixelRatio)); if (canvas.width !== width || canvas.height !== height) { canvas.width = width; canvas.height = height; } }
  function objectPoint(object, local) { const scaled = local.map((value, index) => value * object.scale[index]); const rotated = quatRotate(object.rotation, scaled); return rotated.map((value, index) => value + object.position[index]); }
  function drawGrid() { const center = project([0, 0, 0]); ctx.save(); ctx.lineWidth = 1 * devicePixelRatio; for (let index = -7; index <= 7; index++) { const a = project([index, -2.1, -7]), b = project([index, -2.1, 7]), c = project([-7, -2.1, index]), d = project([7, -2.1, index]); ctx.strokeStyle = index === 0 ? "#46617f" : "#203047"; ctx.beginPath(); ctx.moveTo(a.x * devicePixelRatio, a.y * devicePixelRatio); ctx.lineTo(b.x * devicePixelRatio, b.y * devicePixelRatio); ctx.stroke(); ctx.beginPath(); ctx.moveTo(c.x * devicePixelRatio, c.y * devicePixelRatio); ctx.lineTo(d.x * devicePixelRatio, d.y * devicePixelRatio); ctx.stroke(); } ctx.restore(); }
  function drawObject(object) { const corners = [[-1,-1,-1],[1,-1,-1],[1,1,-1],[-1,1,-1],[-1,-1,1],[1,-1,1],[1,1,1],[-1,1,1]].map((point) => project(objectPoint(object, point))); const edges = [[0,1],[1,2],[2,3],[3,0],[4,5],[5,6],[6,7],[7,4],[0,4],[1,5],[2,6],[3,7]]; ctx.save(); ctx.lineWidth = (object.id === state.selectedId ? 2.6 : 1.4) * devicePixelRatio; ctx.strokeStyle = object.id === state.selectedId ? "#ffffff" : object.color; ctx.fillStyle = `${object.color}24`; ctx.beginPath(); [0,1,2,3].forEach((index, i) => i ? ctx.lineTo(corners[index].x * devicePixelRatio, corners[index].y * devicePixelRatio) : ctx.moveTo(corners[index].x * devicePixelRatio, corners[index].y * devicePixelRatio)); ctx.closePath(); ctx.fill(); for (const [from, to] of edges) { ctx.beginPath(); ctx.moveTo(corners[from].x * devicePixelRatio, corners[from].y * devicePixelRatio); ctx.lineTo(corners[to].x * devicePixelRatio, corners[to].y * devicePixelRatio); ctx.stroke(); } ctx.restore(); }
  function screenAxis(axis) { const [x, y] = AXES[axis].screen, length = Math.hypot(x, y); return [x / length, y / length]; }
  function gizmoCenter() { const point = selected(); return point ? project(point.position) : null; }
  function drawGizmo() { const object = selected(), center = gizmoCenter(); if (!object || !center) return; const cx = center.x * devicePixelRatio, cy = center.y * devicePixelRatio, length = 72 * devicePixelRatio; ctx.save(); if (state.tool === "rotate") { for (const axis of Object.keys(AXES)) { ctx.strokeStyle = AXES[axis].color; ctx.lineWidth = 2 * devicePixelRatio; ctx.setLineDash(axis === "z" ? [] : [5 * devicePixelRatio, 4 * devicePixelRatio]); ctx.beginPath(); ctx.arc(cx, cy, length + Object.keys(AXES).indexOf(axis) * 8 * devicePixelRatio, 0, Math.PI * 2); ctx.stroke(); } ctx.setLineDash([]); ctx.restore(); return; }
    for (const axis of Object.keys(AXES)) { const [x, y] = screenAxis(axis), ex = cx + x * length, ey = cy + y * length; ctx.strokeStyle = AXES[axis].color; ctx.fillStyle = AXES[axis].color; ctx.lineWidth = 3 * devicePixelRatio; ctx.beginPath(); ctx.moveTo(cx, cy); ctx.lineTo(ex, ey); ctx.stroke(); ctx.beginPath(); if (state.tool === "scale") ctx.rect(ex - 5 * devicePixelRatio, ey - 5 * devicePixelRatio, 10 * devicePixelRatio, 10 * devicePixelRatio); else { ctx.arc(ex, ey, 6 * devicePixelRatio, 0, Math.PI * 2); } ctx.fill(); }
    ctx.restore(); }
  function draw() { resize(); ctx.clearRect(0, 0, canvas.width, canvas.height); ctx.fillStyle = "#09111c"; ctx.fillRect(0, 0, canvas.width, canvas.height); drawGrid(); objects.forEach(drawObject); drawGizmo(); }
  function distanceToSegment(px, py, ax, ay, bx, by) { const dx = bx - ax, dy = by - ay, t = clamp(((px - ax) * dx + (py - ay) * dy) / (dx * dx + dy * dy || 1), 0, 1); return Math.hypot(px - (ax + t * dx), py - (ay + t * dy)); }
  function handleAt(x, y) { const center = gizmoCenter(); if (!center) return null; if (state.tool === "rotate") { const radius = Math.hypot(x - center.x, y - center.y); return Math.abs(radius - 72) < 18 ? { kind: "rotate", axis: "z", center } : null; } for (const axis of Object.keys(AXES)) { const [sx, sy] = screenAxis(axis), ex = center.x + sx * 72, ey = center.y + sy * 72; if (state.tool === "scale" && Math.hypot(x - ex, y - ey) < 20) return { kind: "scale", axis, center }; if (state.tool === "translate" && distanceToSegment(x, y, center.x, center.y, ex, ey) < 17) return { kind: "translate", axis, center }; } return null; }
  function pickObject(x, y) { let hit = null, distance = Infinity; for (const object of objects) { const p = project(object.position), d = Math.hypot(x - p.x, y - p.y); if (d < distance) { hit = object; distance = d; } } return distance < 75 ? hit : null; }
  function localAxis(object, axis) { const vector = AXES[axis].vector; return state.space === "local" ? quatRotate(object.rotation, vector) : vector; }
  function pointerPoint(event) { const rect = canvas.getBoundingClientRect(); return [event.clientX - rect.left, event.clientY - rect.top]; }
  function beginDrag(event, handle) { const object = selected(), [x, y] = pointerPoint(event); if (!object) return; try { canvas.setPointerCapture(event.pointerId); } catch { /* Synthetic and remote pointer events may not own a capture target. */ } state.drag = { pointerId: event.pointerId, handle, start: [x, y], transform: cloneTransform(object), angle: Math.atan2(y - handle.center.y, x - handle.center.x) }; setStatus(`${handle.kind} ${handle.axis.toUpperCase()} drag started in ${state.space} space.`); }
  function moveDrag(event) { const drag = state.drag, object = selected(), [x, y] = pointerPoint(event); if (!drag || !object) return; const dx = x - drag.start[0], dy = y - drag.start[1], axis = drag.handle.axis; applyTransform(object, drag.transform); if (drag.handle.kind === "translate") { const [sx, sy] = screenAxis(axis); const delta = snap((dx * sx + dy * sy) / 48, .25); const direction = localAxis(object, axis); object.position = drag.transform.position.map((value, index) => value + direction[index] * delta); } else if (drag.handle.kind === "rotate") { const angle = Math.atan2(y - drag.handle.center.y, x - drag.handle.center.x) - drag.angle; const snapped = snap(angle, degToRad(15)); object.rotation = normalizeQuat(quatMul(quatFromAxis(localAxis(object, axis), snapped), drag.transform.rotation)); } else { const [sx, sy] = screenAxis(axis); const delta = snap((dx * sx + dy * sy) / 150, .1); const index = "xyz".indexOf(axis); object.scale[index] = Math.max(.1, drag.transform.scale[index] * (1 + delta)); } renderUi(); draw(); }
  function transformChanged(before, after) { return JSON.stringify(before) !== JSON.stringify(after); }
  function finishDrag() { const object = selected(), drag = state.drag; if (!object || !drag) return; const after = cloneTransform(object); if (transformChanged(drag.transform, after)) { state.history.push({ label: `${drag.handle.kind} ${drag.handle.axis.toUpperCase()}`, objectId: object.id, before: drag.transform, after }); state.redo.length = 0; state.revision += 1; state.dragCount += 1; setStatus(`Committed ${drag.handle.kind} ${drag.handle.axis.toUpperCase()} as a reversible transform command.`); } state.drag = null; renderUi(); draw(); }
  function applyHistory(direction) { const command = direction === "undo" ? state.history.pop() : state.redo.pop(); if (!command) return; const object = objects.find((item) => item.id === command.objectId); if (!object) return; applyTransform(object, direction === "undo" ? command.before : command.after); (direction === "undo" ? state.redo : state.history).push(command); state.revision += 1; setStatus(`${direction === "undo" ? "Undid" : "Redid"} ${command.label}.`); renderUi(); draw(); }
  function setStatus(message) { $("#status").textContent = message; }
  function renderUi() { const object = selected(); $("#tool-chip").textContent = state.tool[0].toUpperCase() + state.tool.slice(1); $("#space-chip").textContent = state.space[0].toUpperCase() + state.space.slice(1); $("#entity-count").textContent = `${objects.length} entities`; $("#selected-name").textContent = object?.name || "none"; $("#history-size").textContent = String(state.history.length); $("#revision").textContent = String(state.revision); $("#pick-count").textContent = String(state.pickCount); $("#drag-count").textContent = String(state.dragCount); $("#undo").disabled = !state.history.length; $("#redo").disabled = !state.redo.length;
    $("#entities").innerHTML = objects.map((item) => `<button type="button" class="entity ${item.id === state.selectedId ? "active" : ""}" data-entity="${item.id}"><strong>${item.name}</strong><small>${item.id} · ${item.id === state.selectedId ? "active" : "scene object"}</small></button>`).join(""); document.querySelectorAll("[data-entity]").forEach((button) => button.addEventListener("click", () => { state.selectedId = button.dataset.entity; state.pickCount += 1; setStatus(`Selected ${selected().name} from the scene outliner.`); renderUi(); draw(); }));
    const euler = object ? quatToEuler(object.rotation) : [0, 0, 0]; document.querySelectorAll("[data-field]").forEach((input) => { const [group, axis] = input.dataset.field.split("."); const index = "xyz".indexOf(axis); input.value = object ? (group === "rotation" ? euler[index] : object[group][index]).toFixed(2) : ""; input.disabled = !object; }); document.querySelectorAll("[data-tool]").forEach((button) => button.classList.toggle("active", button.dataset.tool === state.tool)); document.querySelectorAll("[data-space]").forEach((button) => button.classList.toggle("active", button.dataset.space === state.space)); }
  function inspectorChange(event) { const object = selected(); if (!object) return; const before = cloneTransform(object), [group, axis] = event.target.dataset.field.split("."), index = "xyz".indexOf(axis), value = Number(event.target.value); if (!Number.isFinite(value)) return; if (group === "rotation") { const euler = quatToEuler(object.rotation); euler[index] = value; object.rotation = quatFromEuler(...euler.map(degToRad)); } else object[group][index] = group === "scale" ? Math.max(.1, value) : value; const after = cloneTransform(object); if (transformChanged(before, after)) { state.history.push({ label: "Inspector edit", objectId: object.id, before, after }); state.redo.length = 0; state.revision += 1; } renderUi(); draw(); }
  $("#add-object").addEventListener("click", () => { const id = `object-${state.nextId++}`, object = makeObject(id, `Object ${state.nextId - 1}`, [-2 + Math.random() * 4, -.8 + Math.random() * 2.6, -1 + Math.random() * 2], [0, 0, 0], [.6, .6, .6], ["#ffb6c0", "#b7ecff", "#d2b4ff"][state.nextId % 3]); objects.push(object); state.selectedId = id; state.revision += 1; setStatus(`Added ${object.name}; select a tool and drag its gizmo.`); renderUi(); draw(); });
  $("#undo").addEventListener("click", () => applyHistory("undo")); $("#redo").addEventListener("click", () => applyHistory("redo")); $("#snap").addEventListener("change", (event) => { state.snap = event.target.checked; setStatus(`Snapping ${state.snap ? "enabled" : "disabled"}.`); });
  document.querySelectorAll("[data-tool]").forEach((button) => button.addEventListener("click", () => { state.tool = button.dataset.tool; $("#shortcut").textContent = { translate: "G", rotate: "R", scale: "S" }[state.tool]; setStatus(`${state.tool} tool active.`); renderUi(); draw(); })); document.querySelectorAll("[data-space]").forEach((button) => button.addEventListener("click", () => { state.space = button.dataset.space; setStatus(`${state.space} reference space active.`); renderUi(); draw(); })); document.querySelectorAll("[data-field]").forEach((input) => input.addEventListener("change", inspectorChange));
  canvas.addEventListener("pointerdown", (event) => { const [x, y] = pointerPoint(event), handle = handleAt(x, y); if (handle) { beginDrag(event, handle); return; } const object = pickObject(x, y); if (object) { state.selectedId = object.id; state.pickCount += 1; setStatus(`Picked ${object.name}; ${state.tool} gizmo ready.`); renderUi(); draw(); } }); canvas.addEventListener("pointermove", moveDrag); canvas.addEventListener("pointerup", finishDrag); canvas.addEventListener("pointercancel", finishDrag);
  window.addEventListener("keydown", (event) => { if (event.target.matches("input")) return; const key = event.key.toLowerCase(); if ((event.metaKey || event.ctrlKey) && key === "z") { event.preventDefault(); applyHistory(event.shiftKey ? "redo" : "undo"); return; } if ({ g: "translate", r: "rotate", s: "scale" }[key]) { state.tool = { g: "translate", r: "rotate", s: "scale" }[key]; $("#shortcut").textContent = key.toUpperCase(); renderUi(); draw(); } });
  renderUi(); draw(); window.addEventListener("resize", draw);
})();
